### ISSUE TITLE
Sporadic segfaults due to stack overflows

### ISSUE THREAD

**Issue by dhil** [wasmfx/wasmfxtime#61]
We have regression. WASI calls on fibers seem to segfault. Here is an example:
```wast
(module
  (type $ft (func))
  (type $ct (cont $ft))
  (import "wasi_snapshot_preview1" "fd_write"
     (func $print (param $fd i32)
                  (param $iovec i32)
                  (param $len i32)
                  (param $written i32) (result i32)))
  (memory 1)
  (export "memory" (memory 0))

  ;; 9 is the offset to write to
  (data (i32.const 9) "something\n")

  (func $f
    (i32.const 0) ;; offset
    (i32.const 9) ;; value start of the string
    (i32.store)

    (i32.const 4)                ;; offset
    (i32.const 11)               ;; value, the length of the string
    (i32.store offset=0 align=2) ;; size_buf_len

    (i32.const 1)   ;; 1 for stdout
    (i32.const 0)   ;; 0 as we stored the beginning of __wasi_ciovec_t
    (i32.const 1)   ;;
    (i32.const 20)  ;; nwritten
    (call $print)
    (drop)
  )
  (elem declare func $f)

  (func $main (export "_start")
    (call $f) ;; works
    ;; the following sequence segfaults
    (ref.func $f)
    (cont.new $ct)
    (resume $ct)
  )
)
```

**Comment by dhil** [comment]
I managed to get a stacktrace before the segfault (the segfault may be a red-herring due to the invariants of backtrace construction being broken by linked stacks):

```
thread 'main' panicked at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/io/mod.rs:192:23:
unexpected error when polling the I/O driver: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: tokio::runtime::io::Driver::turn
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/io/mod.rs:192:23
   3: tokio::runtime::io::Driver::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/io/mod.rs:155:9
   4: tokio::runtime::signal::Driver::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/signal/mod.rs:97:9
   5: tokio::runtime::driver::IoStack::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/driver.rs:166:40
   6: tokio::runtime::time::Driver::park_thread_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/time/mod.rs:246:13
   7: tokio::runtime::time::Driver::park_internal
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/time/mod.rs:209:21
   8: tokio::runtime::time::Driver::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/time/mod.rs:156:9
   9: tokio::runtime::driver::TimeDriver::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/driver.rs:310:51
  10: tokio::runtime::driver::Driver::park_timeout
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/driver.rs:66:9
  11: tokio::runtime::scheduler::current_thread::Context::park_yield::{{closure}}
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:395:13
  12: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:410:19
  13: tokio::runtime::scheduler::current_thread::Context::park_yield
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:394:29
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:677:33
  15: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:68
  16: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
  17: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  20: tokio::runtime::context::set_scheduler
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
  21: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:27
  22: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:638:19
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:175:28
  24: tokio::runtime::context::runtime::enter_runtime
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  25: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:167:9
  26: tokio::runtime::runtime::Runtime::block_on
             at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:311:47
  27: wasmtime_wasi::preview2::in_tokio
             at ./crates/wasi/src/preview2/mod.rs:287:13
  28: wasmtime_wasi::preview2::preview1::sync::in_tokio
             at ./crates/wasi/src/preview2/preview1.rs:551:12
  29: wasmtime_wasi::preview2::preview1::sync::add_wasi_snapshot_preview1_to_linker::{{closure}}
             at ./crates/wasi/src/preview2/preview1.rs:533:5
  30: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4),R>>::into_func::native_call_shim::{{closure}}::{{closure}}
             at ./crates/wasmtime/src/func.rs:1975:41
  31: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  33: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  34: __rust_try
  35: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  36: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  37: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4),R>>::into_func::native_call_shim::{{closure}}
             at ./crates/wasmtime/src/func.rs:1970:29
  38: wasmtime::func::Caller<T>::with::{{closure}}
             at ./crates/wasmtime/src/func.rs:1787:13
  39: wasmtime_runtime::instance::Instance::from_vmctx
             at ./crates/runtime/src/instance.rs:240:9
  40: wasmtime::func::Caller<T>::with
             at ./crates/wasmtime/src/func.rs:1785:9
  41: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1,A2,A3,A4),R>>::into_func::native_call_shim
             at ./crates/wasmtime/src/func.rs:1959:34
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: wasmtime_runtime::continuation::cont_new::{{closure}}
             at ./crates/runtime/src/continuation.rs:117:17
  46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  47: wasmtime_fibre::Suspend<Resume,Yield,Return>::execute::{{closure}}
             at ./crates/fibre/src/lib.rs:171:62
  48: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  49: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  50: __rust_try
  51: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  52: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  53: wasmtime_fibre::Suspend<Resume,Yield,Return>::execute
             at ./crates/fibre/src/lib.rs:171:22
  54: wasmtime_fibre::unix::fiber_start
             at ./crates/fibre/src/unix.rs:149:9
  55: wasmtime_fibre_start
  56: wasmtime_fibre::unix::Fiber::resume
             at ./crates/fibre/src/unix.rs:175:13
  57: wasmtime_fibre::Fiber<Resume,Yield,Return>::resume
             at ./crates/fibre/src/lib.rs:124:9
  58: wasmtime_runtime::continuation::resume
             at ./crates/runtime/src/continuation.rs:162:20
  59: wasmtime_runtime::libcalls::tc_resume
             at ./crates/runtime/src/libcalls.rs:791:5
  60: wasmtime_runtime::libcalls::trampolines::impl_tc_resume::{{closure}}::{{closure}}
             at ./crates/runtime/src/libcalls.rs:128:29
  61: wasmtime_runtime::instance::Instance::from_vmctx
             at ./crates/runtime/src/instance.rs:240:9
  62: wasmtime_runtime::libcalls::trampolines::impl_tc_resume::{{closure}}
             at ./crates/runtime/src/libcalls.rs:127:25
  63: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  64: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  65: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  66: __rust_try
  67: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  68: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  69: wasmtime_runtime::libcalls::trampolines::impl_tc_resume
             at ./crates/runtime/src/libcalls.rs:126:34
  70: <unknown>
  71: <unknown>
  72: wasmtime::func::Func::call_unchecked_raw::{{closure}}
             at ./crates/wasmtime/src/func.rs:915:13
  73: wasmtime_runtime::traphandlers::catch_traps::call_closure
             at ./crates/runtime/src/traphandlers.rs:241:18
  74: wasmtime_setjmp_17_0_0
             at ./crates/runtime/src/helpers.c:66:3
  75: wasmtime_runtime::traphandlers::catch_traps::{{closure}}
             at ./crates/runtime/src/traphandlers.rs:219:13
  76: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with::{{closure}}
             at ./crates/runtime/src/traphandlers.rs:353:44
  77: wasmtime_runtime::traphandlers::tls::set
             at ./crates/runtime/src/traphandlers.rs:724:13
  78: wasmtime_runtime::traphandlers::<impl wasmtime_runtime::traphandlers::call_thread_state::CallThreadState>::with
             at ./crates/runtime/src/traphandlers.rs:353:19
  79: wasmtime_runtime::traphandlers::catch_traps
             at ./crates/runtime/src/traphandlers.rs:217:18
  80: wasmtime::func::invoke_wasm_and_catch_traps
             at ./crates/wasmtime/src/func.rs:1372:22
  81: wasmtime::func::Func::call_unchecked_raw
             at ./crates/wasmtime/src/func.rs:913:9
  82: wasmtime::func::Func::call_unchecked
             at ./crates/wasmtime/src/func.rs:899:9
  83: wasmtime::func::Func::call_impl
             at ./crates/wasmtime/src/func.rs:1069:13
  84: wasmtime::func::Func::call
             at ./crates/wasmtime/src/func.rs:852:9
  85: wasmtime_cli::commands::run::RunCommand::invoke_func
             at ./src/commands/run.rs:515:26
  86: wasmtime_cli::commands::run::RunCommand::load_main_module
             at ./src/commands/run.rs:443:35
  87: wasmtime_cli::commands::run::RunCommand::execute
             at ./src/commands/run.rs:213:15
  88: wasmtime::Wasmtime::execute
             at ./src/bin/wasmtime.rs:83:35
  89: wasmtime::old_cli::main
             at ./src/bin/wasmtime.rs:226:37
  90: wasmtime::main
             at ./src/bin/wasmtime.rs:108:12
  91: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault (core dumped)
```

**Comment by dhil** [comment]
Occasionally, I see
```
thread 'main' panicked at /home/dhil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:295:12:
attempt to calculate the remainder with a divisor of zero
```
rather than `unexpected error when polling the I/O driver: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }`

**Comment by dhil** [comment]
Here is another WASI program which segfaults
```wast
(module
  (type $ft (func (result i32)))
  (type $ct (cont $ft))
  (import "wasi_snapshot_preview1" "sched_yield"
     (func $sched_yield (result i32)))
  (memory 1)
  (export "memory" (memory 0))

  (func $g (result i32)
    (call $sched_yield))
  (elem declare func $g)

  (func $main (export "_start")
    (call $g) ;; works
    (drop)
    ;; this sequence segfaults
    (cont.new $ct (ref.func $g))
    (resume $ct)
    (drop)
  )
)
```

**Comment by dhil** [comment]
This program works as expected
```wast
(module
  (type $ft (func))
  (type $ct (cont $ft))
  (import "wasi_snapshot_preview1" "proc_exit"
     (func $proc_exit (param i32)))
  (memory 1)
  (export "memory" (memory 0))

  (func $h
    (i32.const 42)
    (call $proc_exit))
  (elem declare func $h)

  (func $main (export "_start")
    ;; exits with code 42
    (cont.new $ct (ref.func $h))
    (resume $ct)
  )
)
```

**Comment by frank-emrich** [comment]
It seems that this is simply a stack overflow on the `Fiber`'s stack. 

Perhaps surprisingly the 4k of stack space we allocate are insufficient for WASI calls. I have recorded the following information in gdb when executing the example program above and breaking when reaching `wasmtime::instance::Instance::_get_export` when called as part of the WASI setup.

The table shows the part of the stack from `f` to  `wasmtime::instance::Instance::_get_export` (i.e., in the table, the stack grows downwards):
The first row shows the size of that particular stack frame, the second row shows the distance from the top/beginning of the `Fiber`'s stack in bytes. We can thus interpret the second row as the accumulated size of the stack from the top of the table until that point.

While I don't entirely trust the size data for each stack frame (since this relies on gdb being able to re-construct the value of`rsp` for each frame), I have confirmed manually that the stack pointer in `_get_export` has indeed overflowed. The stack size is indeed 5280 at that point.


|Frame size (Parent RSP - RSP) | Distance from top of stack | Function name 
| --- | --- | --- |
|N/A | 672 | `f` |
|8 | 680 | `?` |
|8 | 688 | `?` |
|176 | 864 | `wasmtime::func::{impl#58}::into_func::native_call_shim<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>` |
|144 | 1008 | `wasmtime::func::Caller<wasmtime_cli::commands::run::Host>::with<wasmtime_cli::commands::run::Host, wasmtime::func::{impl#58}::into_func::native_call_shim::CallResult<i32>, wasmtime::func::{impl#58}::into_func::native_call_shim::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>` |
|192 | 1200 | `wasmtime_runtime::instance::Instance::from_vmctx<wasmtime::func::{impl#58}::into_func::native_call_shim::CallResult<i32>, wasmtime::func::{impl#3}::with::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime::func::{impl#58}::into_func::native_call_shim::CallResult<i32>, wasmtime::func::{impl#58}::into_func::native_call_shim::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>>` |
|192 | 1392 | `wasmtime::func::{impl#3}::with::{closure#0}<wasmtime_cli::commands::run::Host, wasmtime::func::{impl#58}::into_func::native_call_shim::CallResult<i32>, wasmtime::func::{impl#58}::into_func::native_call_shim::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>` |
|448 | 1840 | `wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>` |
|16 | 1856 | `std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>, core::result::Result<i32, anyhow::Error>>` |
|192 | 2048 | `std::panicking::try<core::result::Result<i32, anyhow::Error>, core::panic::unwind_safe::AssertUnwindSafe<wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>>` |
|32 | 2080 | `__rust_try` |
|112 | 2192 | `std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>, core::result::Result<i32, anyhow::Error>>` |
|80 | 2272 | `core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<i32, anyhow::Error>, wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>>` |
|48 | 2320 | `core::ops::function::FnOnce::call_once<wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure_env#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>, ()>` |
|320 | 2640 | `wasmtime::func::{impl#58}::into_func::native_call_shim::{closure#0}::{closure#0}<wasmtime_cli::commands::run::Host, wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure_env#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>, i32, i32, i32, i32, core::result::Result<i32, anyhow::Error>>` |
|464 | 3104 | `wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure#26}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>` |
|272 | 3376 | `wiggle::run_in_dummy_executor<wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure#26}::{async_block_env#0}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>>` |
|1152 | 4528 | `wasmtime_wasi::sync::snapshots::preview_1::add_wasi_snapshot_preview1_to_linker::{closure#26}::{async_block#0}<wasmtime_cli::commands::run::Host, wasi_common::ctx::WasiCtx, wasmtime_cli::commands::run::{impl#0}::populate_with_wasi::{closure_env#0}>` |
|96 | 4624 | `wasmtime::func::Caller<wasmtime_cli::commands::run::Host>::get_export<wasmtime_cli::commands::run::Host>` |
|128 | 4752 | `wasmtime::instance::Instance::get_export<&mut wasmtime::store::context::StoreContextMut<wasmtime_cli::commands::run::Host>>` |
|528 | 5280 | `wasmtime::instance::Instance::_get_export` |

**Comment by dhil** [comment]
Excellent. We need to reinstall stack checks in some capacity to guard against this behaviour. And also we should work on growable stacks...

**Comment by dhil** [comment]
Closing as I realise this issue has actually been reduced to a duplicate of #26.
